### ISSUE TITLE
Lines 1325-1328  of bluenote/bluenote.gms 

### ISSUE THREAD

**Issue by merrickj** [uw-windc/windc_build#13]
I assume each line here should say `.LO` instead of `.L`
`CD_H.L(r,dg,h) = 0.1 * cd0_hloop(r,dg,h);
WAGE.L(r,q,h) = 0.1 * le0loop(r,q,h);
INT.L(r,h) = 0.1 * ke0loop(r,h);
SAVE.L(r,h) = 0.1 * sav0loop(r,h);`

**Comment by mitchphillipson** [comment]
The bluenote build is currently undergoing a complete rebuild, that may not make our next release (hopefully soon). 

But I going to guess you are correct given the `* Set lower bounds on key variables:` comment. I'll fix this for our next release.

Thanks for identifying it!

**Comment by mitchphillipson** [comment]
Fixed with Pull Request #24
