### ISSUE TITLE
Supply table subset load in sectordisagg.gms

### ISSUE THREAD

**Issue by jonmbecker** [uw-windc/windc_build#8]
Wanted to add this as an open issue. Line 93 of bluenote/sectordisagg.gms:

`ys0(yr_det,j(ir_supply),i(jc_supply)) = supply_det_units(yr_det,ir_supply,jc_supply,'millions of us dollars (USD)');`

Pretty sure this should be:

`ys0(yr_det,j(**jc_supply**),i(**ir_supply**)) = supply_det_units(yr_det,ir_supply,jc_supply,'millions of us dollars (USD)');`

It doesn't make a big difference at the moment, but might cause issues if not fixed for special cases.

EX: could possibly affect a case where federal and state electric utilities ele_fen and ele_sle needs to disaggregate ele_uti from sle and fen.

**Comment by mitchphillipson** [comment]
I'll bring this up with Tom. I'm slowly teaching Tom github so these issues should get addressed more quickly.

We are planning a rebuild of the bluenote module, but it probably won't make the next release.
